services:
  - type: web
    name: artiste
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: LASTFM_API_KEY
        sync: false

  - type: cron
    name: artiste-pipeline
    runtime: python
    schedule: "0 12 * * *"
    buildCommand: pip install -r requirements.txt
    startCommand: python pipeline.py
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: LASTFM_API_KEY
        sync: false
